### PR TITLE
[mod] rename kernel-* commands into linuxdoc.* commands & add man pages

### PR DESCRIPTION
**Pull request by return42**
Rename commands:

- `kernel-doc     --> linuxdoc.rest`
- `kernel-autodoc --> linuxdoc.autodoc`
- `kernel-lintdoc --> linuxdoc.lintdoc`
- `kernel-grepdoc --> linuxdoc.grepdoc`

build man pages::

    $ make man
    ...
    MAN1      [linuxdoc.autodoc] --> man:///share/linuxdoc/dist/man1/linuxdoc.autodoc.1
    MAN1      [linuxdoc.grepdoc] --> man:///share/linuxdoc/dist/man1/linuxdoc.grepdoc.1
    MAN1      [linuxdoc.lint] --> man:///share/linuxdoc/dist/man1/linuxdoc.lint.1
    MAN1      [linuxdoc.rest] --> man:///share/linuxdoc/dist/man1/linuxdoc.rest.1

closes: https://github.com/return42/linuxdoc/pull/28

### CODE REVIEW

**Comment by sanjayankur31** [comment]
I think this looks good (although I haven't tested out the new makefile etc.).

The one thing to note here is that this is quite a major change---folks using the `kernel...` binaries in their pipelines will find that they now break. So, this should be announced as a backwards incompatible major change (with a major version bump, but not sure how that works in calendar versioning?).

**Comment by return42** [comment]
> The one thing to note here is that this is quite a major change---folks using the kernel... binaries in their pipelines will find that they now break.

I dont't think so: the old implementations of this commands had bugs and quirks.  FWIW I added two commits:

- [3679bc9](https://github.com/return42/linuxdoc/pull/30/commits/3679bc984f040b1a9e41b169cfa9033b9f40f55a): [deprecated] compatibility: add entry-points for the kernel-xyz commands 
- [d33d43c](https://github.com/return42/linuxdoc/pull/30/commits/d33d43cd1b40e99caa0b9d40b4eb29a0d90c54df): [mod] add CHANGELOG 

>  but not sure how that works in calendar versioning?

We use the YYYMMDD pattern for releases / in sense of semantic versioning, each new version changes the major number of the version string.

For the users:

- To document major changes, a CHANGELOG file has been added.
- In the new `linuxdoc.deprecated` module we can hold backward compatibility for a while, by example we can drop the deprecated kernel-doc* commands in 2024MMDD release.

**Comment by sanjayankur31** [comment]
Sounds good, thanks!

**Comment by return42** [comment]
I merged this PR into master .. @musicinmybrain, @sanjayankur31 is there anything else you miss?  Otherwise I would build a new release on pypi.org.

**Comment by return42** [comment]
ping

> I merged this PR into master .. @musicinmybrain, @sanjayankur31 is there anything else you miss?  Otherwise I would build a new release on pypi.org.

**Pull request merged**
